import type { Metadata } from "next";
import { Poppins} from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

// const roboto = Roboto({
//       weight: '400',
//       subsets: ['latin'],
//       display: 'swap',
//     })

  const poppins = Poppins({weight:"400",});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
